### TYPE YOUR NAME HERE: Gabriel Ferraz

# ISM 5644 - Programming for Analytics

## Lab Exercise: Numpy Basics

### Overview:
This lab covers operations related to basic Numpy operations and methods / functions.

### Task:
The code cells in this notebook have been left blank. Your task is to complete these cells and provide the execution results. The corresponding question text for each code cell is provided above the cell. 

### Important: Do <u>not</u> forget to run the cells before submitting your work.


### Questions: Please note that there are multiple steps in each question. You should complete the steps in sequence to make sure that the final output is correct.

#### 1. Please complete the steps below.
* Create an array (Numpy ndarray) of integers between 0 and 10.
* Replace the even numbers in the array with -1 and print out the result. <br><br>
Hint: Try to complete the 2nd step without using loops. For instance, you can use boolean indexing (i.e., pass True/False array to the original array as an index) and do the assignment in the same line.

In [31]:
import numpy as np
arr = np.arange(11)
replaced_arr = arr%2 == 0
arr[replaced_arr] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9 -1]


#### 2. Please complete the steps below.
* Create an array of integers between 0 and 30.
* Obtain all the elements that are greater than 10 and that can be divided by 9 from this array. Store the output as a <u>list</u> and print it out. Try to complete this operation without using loops.

In [144]:
arr = np.arange(31)
#print(arr)

new_arr = (arr > 10) & (arr%9 == 0)
#print(new_arr)
alist = [int(i) for i in arr[new_arr]]
print(alist)

[18, 27]


#### 3. Please complete the steps below in sequence (i.e., the output from the current step should be the input of the next step)
* Create a 2D array in the following form:<br>
[[1, 5, 12], <br>
[3, 2, 8], <br>
[19, 4, 9]]
  * Hint: You can use the np.array() method and copy/paste the list as an input.
* Swap columns 1 and 3 and print out the result.
  * Hint: You can use fancy indexing.
* Swap rows 2 and 3 and print out the result.
* Sort the rows in modified array by the 1st column, while preserving the relationship within row values.
  * Notice that a simple sort method/function would not work here as by default "sort" treats each row/column as independent.
  * Hint: You can use argsort to find sorted indices and then pass these values to the array using fancy indexing.

In [55]:
arr = np.array([[1, 5, 12],[3, 2, 8],[19, 4, 9]])
n_column = arr[:, [2,1,0]]
print(n_column)
print('###')
n_rows = n_column[[0,2,1], :]
print(n_rows)
sorted_nrows = n_rows[:, 0].argsort()
print('###')
print(n_rows[sorted_nrows])

[[12  5  1]
 [ 8  2  3]
 [ 9  4 19]]
###
[[12  5  1]
 [ 9  4 19]
 [ 8  2  3]]
###
[[ 8  2  3]
 [ 9  4 19]
 [12  5  1]]


#### 4. Please complete the steps below.
* Initialize two objects: 1) a 10x2 numpy array filled with zeros, 2) a list of integers between 10 and 20 (excluding 20).
* Iterate over the list (for loop) and modify the values in the array as follows:
  * If the list element is an even number, assign value 1 to the 1st column of the corresponding index in the array
  * If the list element is an odd number, assign value 1 to the 2nd column of the corresponding index in the array
* For instance, the first element in the list is 10, an even number, therefore array[0,0] should be 1.
* Print out the modified array.

In [64]:
arr = np.zeros((10,2))
alist = [10,11,12,13,14,15,16,17,18,19]
row = 0

for i in alist:
    if i % 2 == 0:
        arr[row, 0] = 1
    else:
        arr[row, 1] = 1
    row += 1
    
print(arr)

[[1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]


#### 5. Please complete the steps below.
* Initialize a 1D array with the following integers: 15,12,2,43,12,6,6,15,8,2
* Some of the numbers above are repeated. Create a new array that includes all the numbers from the original array, but without any duplicates. The new array should preserve the order from the old one.
* Find the duplicated elements in the original array and print them out.

In [81]:
arr = np.array([15,12,2,43,12,6,6,15,8,2])
check = []
duplicates = []

for i in arr:
    if i not in check:
        check.append(i)
    else:
        duplicates.append(i)
        
newlist = np.array(check)
duplicateslist = np.array(duplicates)

print(newlist)
print(duplicateslist)

[15 12  2 43  6  8]
[12  6 15  2]


#### 6. Please complete the steps below.
* Create a 1D array containing the following quantities sold for four products: [15, 24, 8, 12]
* Create a second 1D array containing their respective wholesale prices: [10.50, 4.99, 25.00, 15.75]
* Calculate the total revenue per product by multiplying the two arrays element-wise.
* Convert the resulting revenue array into 64-bit integers using the .astype() method to round down to whole-dollar values, and print out the final array.

In [92]:
arr = np.array([15,24,8,12])
barr = np.array([10.50,4.99,25.00,15.75])

result = arr * barr
resultint = result.astype(int)

print(resultint)

[157 119 200 189]


#### 7. Please complete the steps below.
* Create two 1D arrays tracking daily attendance over a 4-day period for two business branches:<br>
  Branch 1: [18, 32, 14, 25]<br>
  Branch 2: [22, 11, 29, 15]<br>
* Combine these two arrays into a single 8-day history array using the np.concatenate() function.
* Use the np.where() function on the combined array to flag busy periods. If attendance is 20 or greater, replace the value with the string 'High'. If it is less than 20, replace it with the string 'Low'. Print out this final flagged array.

In [101]:
arr = ([18, 32, 14, 25])
barr = ([22, 11, 29, 15])
combined = np.concatenate((arr, barr), axis = 0)
attendance = np.where(combined > 20, 'high', 'low' )

print(attendance)

['low' 'high' 'low' 'high' 'high' 'low' 'high' 'low']


#### 8. Data Question: Import the "iris_full_numpy.csv" dataset into a numpy array, while skipping the 1st row (feature names). The data contains 50 samples from each of three species of Iris flowers (Setosa, Verginica, and Versicolor). Four features were measured for each sample.
Hint: Notice that: 1) data values are separated by commas and 2) the data is non-homogenous - i.e., it includes float and string values. If using numpy's loadtxt method, you'd need to configure it using delimiter and dtype arguments.

In [103]:
arr = np.loadtxt('iris_full_numpy.csv', delimiter = ',', skiprows = 1, dtype = 'str')

#### 8.1. Please complete the steps below:
* Subset columns 1 to 4 into a new array called x. Then, convert array x to "float" data type.
* Subset the last column into a new array called yStr.

In [125]:
x = arr[:, :4]
x_float = x.astype(float)
yStr = arr[:, -1]
print(yStr)

['Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa' 'Setosa'
 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor' 'Versicolor'
 'Versicolor' 'Versicolor' 'V

#### 8.2. Please complete the steps below:
* Create an array named "y" that stores the integer value representations of yStr observations. In other words, convert categorical y values to indicator ones. Each unique value in yStr should be encoded as an integer.
  * For instance, if yStr = array([Setosa,Setosa,Verginica,Versicolor]), then y = array([0,0,1,2])
* Do not use hard coding.

In [126]:
a = np.unique(yStr)
y = np.zeros(yStr.shape, dtype = int)
for index, item in enumerate(a):
    y[np.where(yStr==item)] = index
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


#### 8.3. Please complete the steps below:
* Combine x and y arrays along axis 1 (horizontally) into a new array called combinedArr

In [130]:
combinedArr = np.column_stack((x_float, y))
print(combinedArr)

[[0.2 1.4 3.5 5.1 0. ]
 [0.2 1.4 3.  4.9 0. ]
 [0.2 1.3 3.2 4.7 0. ]
 [0.2 1.5 3.1 4.6 0. ]
 [0.2 1.4 3.6 5.  0. ]
 [0.4 1.7 3.9 5.4 0. ]
 [0.3 1.4 3.4 4.6 0. ]
 [0.2 1.5 3.4 5.  0. ]
 [0.2 1.4 2.9 4.4 0. ]
 [0.1 1.5 3.1 4.9 0. ]
 [0.2 1.5 3.7 5.4 0. ]
 [0.2 1.6 3.4 4.8 0. ]
 [0.1 1.4 3.  4.8 0. ]
 [0.1 1.1 3.  4.3 0. ]
 [0.2 1.2 4.  5.8 0. ]
 [0.4 1.5 4.4 5.7 0. ]
 [0.4 1.3 3.9 5.4 0. ]
 [0.3 1.4 3.5 5.1 0. ]
 [0.3 1.7 3.8 5.7 0. ]
 [0.3 1.5 3.8 5.1 0. ]
 [0.2 1.7 3.4 5.4 0. ]
 [0.4 1.5 3.7 5.1 0. ]
 [0.2 1.  3.6 4.6 0. ]
 [0.5 1.7 3.3 5.1 0. ]
 [0.2 1.9 3.4 4.8 0. ]
 [0.2 1.6 3.  5.  0. ]
 [0.4 1.6 3.4 5.  0. ]
 [0.2 1.5 3.5 5.2 0. ]
 [0.2 1.4 3.4 5.2 0. ]
 [0.2 1.6 3.2 4.7 0. ]
 [0.2 1.6 3.1 4.8 0. ]
 [0.4 1.5 3.4 5.4 0. ]
 [0.1 1.5 4.1 5.2 0. ]
 [0.2 1.4 4.2 5.5 0. ]
 [0.2 1.5 3.1 4.9 0. ]
 [0.2 1.2 3.2 5.  0. ]
 [0.2 1.3 3.5 5.5 0. ]
 [0.1 1.4 3.6 4.9 0. ]
 [0.2 1.3 3.  4.4 0. ]
 [0.2 1.5 3.4 5.1 0. ]
 [0.3 1.3 3.5 5.  0. ]
 [0.3 1.3 2.3 4.5 0. ]
 [0.2 1.3 3.2 4.4 0. ]
 [0.6 1.6 3

#### 8.4. Please complete the steps below:
* Split both x and y arrays into two parts (train and test). So, you should have 4 new arrays: 1) xTrain, 2)xTest, 3) yTrain, 4) yTest.
  * 70% of the data should go into the train dataset and 30% of the data should go into the test dataset. Allocation should be made randomly.
  * When splitting the data, the order of the observations across the x and y arrays should be preserved.
  * For instance, if you assign the 2nd observation into the test dataset, then both xTest and yTest should include the 2nd observation from their original arrays.
  * Do <u>NOT</u> use pre-built functions from external packages (e.g., scikit-learn). Only Numpy and plain Python functions are allowed. <br><br>

Hints:
1. Numpy's random.shuffle function might be helpful. Specifically, you can shuffle an ordered array that is the same length as the data and slice the shuffled array with a 70/30 ratio to identify the indices for train and test sets.

In [140]:
data_shape = np.arange(x_float.shape[0])
np.random.shuffle(data_shape)
xrandom = x_float[data_shape]
yrandom = y[data_shape]
split = int(len(xrandom)*.70)

xTrain = xrandom[:split]
xTest = xrandom[split:]
yTrain = yrandom[split:]
yTest = yrandom[:split]

print('xTrain:', xTrain.shape, 'xTest:', xTest.shape)
print('yTrain:', yTrain.shape, 'yTest:', yTest.shape)

xTrain: (105, 4) xTest: (45, 4)
yTrain: (45,) yTest: (105,)


#### 8.5. Please complete the steps below:
* Find the mean of each column in xTest.
* Find the maximum value of each row in xTest.

In [137]:
xTestavg = np.mean(xTest, axis = 0)
xTestmax = np.max(xTest, axis = 1)
print(xTestavg)
print(xTestmax)

[1.23333333 3.94222222 2.99333333 5.86888889]
[6.  5.4 4.4 6.1 6.1 6.  4.8 4.9 6.5 6.2 5.  4.5 6.1 6.1 6.1 5.5 7.3 6.4
 4.8 5.8 6.9 5.8 6.3 5.6 5.7 5.1 5.2 6.5 6.  6.3 5.7 7.7 6.7 5.7 7.7 5.6
 7.2 4.9 6.4 4.7 5.  6.3 4.9 5.5 6.7]
